export const sampleData = [
  {
    "Union Local": "Local 67",
    "Employee Name": "Mark Arm",
    "Employee ID": 2247,
    "Total RPT HRS": 155,
    "Gross Wages": 6565.8,
    rows: [
      {
        "Job Name": "Meadows Express",
        "Job ID": "#12875-A",
        Classification: "G1-General Building, PS-90",
        "Agreement Name": "123-Construction",
        "Rate (Hourly)": 62.46,
        values: {
          st: {
            m: 5,
            tu: 5,
            w: 5,
            th: 5,
            f: 5,
            sa: 5,
            su: 5,
          },
          ot: {
            m: 1,
            tu: 1,
            w: 1,
            th: 1,
            f: 1,
            sa: 1,
            su: 1,
          },
          dt: {
            m: 2,
            tu: 2,
            w: 2,
            th: 2,
            f: 2,
            sa: 2,
            su: 2,
          },
        },
        Expenses: 0,
        EarningCode: "1857687-98",
        CostCenter: "1857687-98",
      },
      {
        "Job Name": "Meadows Express",
        "Job ID": "#12875-A",
        Classification: "G1-General Building, PS-90",
        "Agreement Name": "123-Construction",
        "Rate (Hourly)": 62.46,
        values: {
          st: {
            m: 5,
            tu: 5,
            w: 5,
            th: 5,
            f: 5,
            sa: 5,
            su: 5,
          },
          ot: {
            m: 1,
            tu: 1,
            w: 1,
            th: 1,
            f: 1,
            sa: 1,
            su: 1,
          },
          dt: {
            m: 2,
            tu: 2,
            w: 2,
            th: 2,
            f: 2,
            sa: 2,
            su: 2,
          },
        },
        Expenses: 0,
        EarningCode: "1857687-98",
        CostCenter: "1857687-98",
      },
    ],
  },
  {
    "Union Local": "Local 82",
    "Employee Name": "Chris Cornell",
    "Employee ID": 3381,
    "Total RPT HRS": 142,
    "Gross Wages": 7234.5,
    rows: [
      {
        "Job Name": "Riverside Plaza",
        "Job ID": "#13492-B",
        Classification: "G2-Commercial, PS-95",
        "Agreement Name": "456-Commercial",
        "Rate (Hourly)": 68.75,
        values: {
          st: { m: 8, tu: 8, w: 8, th: 8, f: 8, sa: 0, su: 0 },
          ot: { m: 2, tu: 0, w: 1, th: 0, f: 2, sa: 0, su: 0 },
          dt: { m: 0, tu: 0, w: 0, th: 0, f: 0, sa: 4, su: 0 },
        },
        Expenses: 150,
        EarningCode: "1857699-01",
        CostCenter: "1857699-01",
      },
    ],
  },
  {
    "Union Local": "Local 15",
    "Employee Name": "Eddie Vedder",
    "Employee ID": 4472,
    "Total RPT HRS": 168,
    "Gross Wages": 8892.3,
    rows: [
      {
        "Job Name": "Harbor Heights",
        "Job ID": "#14721-C",
        Classification: "G3-Industrial, PS-100",
        "Agreement Name": "789-Industrial",
        "Rate (Hourly)": 72.9,
        values: {
          st: { m: 10, tu: 10, w: 10, th: 10, f: 10, sa: 0, su: 0 },
          ot: { m: 2, tu: 2, w: 2, th: 2, f: 2, sa: 0, su: 0 },
          dt: { m: 0, tu: 0, w: 0, th: 0, f: 0, sa: 6, su: 4 },
        },
        Expenses: 275,
        EarningCode: "1857722-05",
        CostCenter: "1857722-05",
      },
      {
        "Job Name": "Skyline Tower",
        "Job ID": "#14722-D",
        Classification: "G3-Industrial, PS-100",
        "Agreement Name": "789-Industrial",
        "Rate (Hourly)": 72.9,
        values: {
          st: { m: 0, tu: 0, w: 0, th: 0, f: 0, sa: 8, su: 8 },
          ot: { m: 0, tu: 0, w: 0, th: 0, f: 0, sa: 2, su: 2 },
          dt: { m: 0, tu: 0, w: 0, th: 0, f: 0, sa: 0, su: 0 },
        },
        Expenses: 125,
        EarningCode: "1857722-06",
        CostCenter: "1857722-06",
      },
    ],
  },
];
