export const sampleData = [
  {
    "Union Local": "Local 67",
    "Employee Name": "Mark Arm",
    "Employee ID": 2247,
    "Total RPT HRS": 155,
    "Gross Wages": 6565.8,
    rows: [
      {
        "Job Name": "Meadows Express",
        "Job ID": "#12875-A",
        Classification: "G1-General Building, PS-90",
        "Agreement Name": "123-Construction",
        "Rate (Hourly)": 62.46,
        values: {
          st: {
            m: 5,
            tu: 5,
            w: 5,
            th: 5,
            f: 5,
            sa: 5,
            su: 5,
          },
          ot: {
            m: 1,
            tu: 1,
            w: 1,
            th: 1,
            f: 1,
            sa: 1,
            su: 1,
          },
          dt: {
            m: 2,
            tu: 2,
            w: 2,
            th: 2,
            f: 2,
            sa: 2,
            su: 2,
          },
        },
        Expenses: 0,
        EarningCode: "1857687-98",
        CostCenter: "1857687-98",
      },
      {
        "Job Name": "Meadows Express",
        "Job ID": "#12875-A",
        Classification: "G1-General Building, PS-90",
        "Agreement Name": "123-Construction",
        "Rate (Hourly)": 62.46,
        values: {
          st: {
            m: 5,
            tu: 5,
            w: 5,
            th: 5,
            f: 5,
            sa: 5,
            su: 5,
          },
          ot: {
            m: 1,
            tu: 1,
            w: 1,
            th: 1,
            f: 1,
            sa: 1,
            su: 1,
          },
          dt: {
            m: 2,
            tu: 2,
            w: 2,
            th: 2,
            f: 2,
            sa: 2,
            su: 2,
          },
        },
        Expenses: 0,
        EarningCode: "1857687-98",
        CostCenter: "1857687-98",
      },
    ],
  },
];
